spring:
  application:
    name: user-service
server:
  port: 8080

#data-sources:
#  - name: ${DB-1}
#    strategy: postgres
#    url: jdbc:postgresql://localhost:5432/db1
#    table: users
#    user: testuser
#    password: testpass
#    mapping:
#      id: user_id
#      username: login
#      name: first_name
#      surname: last_name
#  - name: database2
#    strategy: postgres
#    url: jdbc:postgresql://localhost:5432/db2
#    table: user_table
#    user: anotheruser
#    password: anotherpass
#    mapping:
#      id: ldap_login
#      username: ldap_login
#      name: name
#      surname: surname